name: quick_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  flutter_animate: ^4.5.0
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  easy_localization: ^3.0.7
  go_router: ^14.3.0
  json_annotation: ^4.9.0
  top_snackbar_flutter: ^3.1.0
  vector_graphics: ^1.1.15
  shared_preferences: ^2.3.1
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  #firebase
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  firebase_auth: ^5.3.4
  firebase_storage: ^12.3.7
  cloud_firestore: ^5.6.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.0.0 # Specify the correct version, remove if unused.
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  freezed: ^2.5.7
  json_serializable: ^6.6.2 # Recommended for model serialization
  mockito: ^5.4.2 # Optional: For mocking in unit tests
  test: ^1.22.0 # Optional: For standalone Dart testing

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/fonts/
    - i18n/
    - .env

  fonts:
    - family: AlexBrush
      fonts:
        - asset: assets/fonts/AlexBrush-Regular.ttf

    - family: alexandria
      fonts:
        - asset: assets/fonts/Alexandria.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish/static/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish/static/Mulish-Black.ttf
          weight: 400

flutter_gen:
  output: lib/gen
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
  colors:
    inputs:
      - assets/colors/colors.xml
