name: quick_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  go_router: ^14.3.0
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.2
  top_snackbar_flutter: ^3.1.0
  cached_network_image: ^3.4.1
  flutter_gen: ^5.7.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner:

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/fonts/
    - .env

  fonts:
    - family: AlexBrush
      fonts:
        - asset: assets/fonts/AlexBrush-Regular.ttf

    - family: alexandria
      fonts:
        - asset: assets/fonts/Alexandria.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

flutter_gen:
  output: lib/gen
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
  colors:
    inputs:
      - assets/colors/colors.xml
